language: rust
os:
    - linux
    - osx
env:
    global:
        - secure: J7L/6+Tgg6t5gLpziHyr9A05sgUEE5u49WXLGtkGQTOIghVryAwEdRRuFZ6Wn2jTrL/mA7bISWG82F3UowaDY4YvsxL/3uxcgpwKvRmqpauTG/FY0T/UBhA9vK+qtaWEY9MvifhI39nw2xYkymzdMPMFKbXj6jsFNdugw3OZb2k=
before_install:
    - sudo add-apt-repository --yes ppa:hansjorg/rust
    - sudo add-apt-repository --yes ppa:cmrx64/cargo
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq rust-nightly cargo
script:
    - cargo build -v
    - cargo test  -v
    - cargo doc   -v
after_script:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
